Repository PlateSwipe/PlateSwipe, pull requests merged in 2024-12, with the labels that each got.

#255 Fix/fridge backend
  app/src/main/java/com/android/sample/model/user/UserRepositoryFirestore.kt
  app/src/test/java/com/android/sample/model/user/UserRepositoryFirestoreTest.kt
Labels: bug

#254 Feature/fridge UI
  app/src/androidTest/java/com/android/sample/account/AccountScreenTest.kt
  app/src/androidTest/java/com/android/sample/authentication/SignInScreenTest.kt
  app/src/androidTest/java/com/android/sample/createRecipe/PublishRecipeScreenTest.kt
  app/src/androidTest/java/com/android/sample/createRecipe/RecipeIngredientsScreenTest.kt
  app/src/androidTest/java/com/android/sample/e2e/End2EndTest.kt
  app/src/androidTest/java/com/android/sample/fridge/EditFridgeItemTest.kt
  app/src/androidTest/java/com/android/sample/fridge/FridgeScreenTest.kt
  app/src/androidTest/java/com/android/sample/screen/RecipeOverviewTest.kt
  app/src/androidTest/java/com/android/sample/search/SearchIngredientScreenTest.kt
  app/src/androidTest/java/com/android/sample/utils/CounterTest.kt
  app/src/androidTest/java/com/android/sample/utils/RecipeListTest.kt
  app/src/main/java/com/android/sample/MainActivity.kt
  app/src/main/java/com/android/sample/model/ingredient/IngredientViewModel.kt
  app/src/main/java/com/android/sample/model/ingredient/SearchIngredientViewModel.kt
  app/src/main/java/com/android/sample/model/user/UserViewModel.kt
  app/src/main/java/com/android/sample/resources/C.kt
  app/src/main/java/com/android/sample/ui/camera/CameraScanCodeBarScreen.kt
  app/src/main/java/com/android/sample/ui/createRecipe/ListIngredientScreen.kt
  app/src/main/java/com/android/sample/ui/fridge/EditFridgeItemScreen.kt
  app/src/main/java/com/android/sample/ui/fridge/FridgeScreen.kt
  app/src/main/java/com/android/sample/ui/navigation/NavigationActions.kt
  app/src/main/java/com/android/sample/ui/recipeOverview/RecipeOverview.kt
  app/src/main/java/com/android/sample/ui/searchIngredient/SearchIngredientScreen.kt
  app/src/main/java/com/android/sample/ui/swipePage/SwipePage.kt
  app/src/main/java/com/android/sample/ui/theme/Color.kt
  app/src/main/java/com/android/sample/ui/utils/Counter.kt
  app/src/main/java/com/android/sample/ui/utils/PlateSwipeButton.kt
  app/src/main/java/com/android/sample/ui/utils/SampleClasses.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/android/sample/model/ingredient/IngredientViewModelTest.kt
  app/src/test/java/com/android/sample/model/user/UserViewModelTest.kt
Labels: enhancement

#266 feat: add edit mode for recipes with state management and tests
  app/src/androidTest/java/com/android/sample/account/AccountScreenTest.kt
  app/src/androidTest/java/com/android/sample/createRecipe/CreateRecipeScreenTest.kt
  app/src/androidTest/java/com/android/sample/createRecipe/OptionalInformationScreenTest.kt
  app/src/androidTest/java/com/android/sample/createRecipe/RecipeNameScreenTest.kt
  app/src/androidTest/java/com/android/sample/e2e/End2EndTest.kt
  app/src/androidTest/java/com/android/sample/utils/RecipeListTest.kt
  app/src/main/java/com/android/sample/MainActivity.kt
  app/src/main/java/com/android/sample/model/recipe/CreateRecipeViewModel.kt
  app/src/main/java/com/android/sample/model/recipe/RecipeBuilder.kt
  app/src/main/java/com/android/sample/resources/C.kt
  app/src/main/java/com/android/sample/ui/account/AccountScreen.kt
  app/src/main/java/com/android/sample/ui/createRecipe/CreateRecipeScreen.kt
  app/src/main/java/com/android/sample/ui/createRecipe/OptionalInformationScreen.kt
  app/src/main/java/com/android/sample/ui/createRecipe/RecipeIngredientsScreen.kt
  app/src/main/java/com/android/sample/ui/createRecipe/RecipeNameScreen.kt
  app/src/main/java/com/android/sample/ui/navigation/NavigationActions.kt
  app/src/main/java/com/android/sample/ui/utils/RecipeList.kt
  app/src/main/res/drawable/pencil.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/android/sample/model/recipe/CreateRecipeViewModelTest.kt
  app/src/test/java/com/android/sample/model/recipe/RecipeBuilderTest.kt
Labels: enhancement

#258 feature/edit account ui
  app/src/androidTest/java/com/android/sample/account/EditAccountScreenTest.kt
  app/src/main/java/com/android/sample/MainActivity.kt
  app/src/main/java/com/android/sample/model/user/User.kt
  app/src/main/java/com/android/sample/model/user/UserRepositoryFirestore.kt
  app/src/main/java/com/android/sample/model/user/UserViewModel.kt
  app/src/main/java/com/android/sample/resources/C.kt
  app/src/main/java/com/android/sample/ui/account/AccountScreen.kt
  app/src/main/java/com/android/sample/ui/account/EditAccountScreen.kt
  app/src/main/java/com/android/sample/ui/navigation/NavigationActions.kt
  app/src/main/java/com/android/sample/ui/utils/PlateSwipeScaffold.kt
  app/src/main/java/com/android/sample/ui/utils/SampleClasses.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/android/sample/model/user/UserRepositoryFirestoreTest.kt
  app/src/test/java/com/android/sample/model/user/UserTest.kt
Labels: enhancement

#257 Feature/filter page backend
  app/src/androidTest/java/com/android/sample/screen/FilterPageTest.kt
  app/src/androidTest/java/com/android/sample/screen/RecipeOverviewTest.kt
  app/src/androidTest/java/com/android/sample/screen/SwipePageTest.kt
  app/src/main/java/com/android/sample/model/filter/Filter.kt
  app/src/main/java/com/android/sample/model/filter/FilterPageViewModel.kt
  app/src/main/java/com/android/sample/model/recipe/DefaultRecipeRepository.kt
  app/src/main/java/com/android/sample/model/recipe/RecipesRepository.kt
  app/src/main/java/com/android/sample/model/recipe/RecipesViewModel.kt
  app/src/main/java/com/android/sample/model/recipe/networkData/FirestoreRecipesRepository.kt
  app/src/main/java/com/android/sample/model/recipe/networkData/MealDBRecipesRepository.kt
  app/src/main/java/com/android/sample/model/recipe/networkData/RecipeNetworkRepository.kt
  app/src/main/java/com/android/sample/resources/C.kt
  app/src/main/java/com/android/sample/ui/filter/FilterPage.kt
  app/src/main/java/com/android/sample/ui/swipePage/SwipePage.kt
  app/src/test/java/com/android/sample/model/filter/FilterTest.kt
  app/src/test/java/com/android/sample/model/recipe/DefaultRecipeRepositoryTest.kt
  app/src/test/java/com/android/sample/model/recipe/RecipesViewModelTest.kt
  app/src/test/java/com/android/sample/model/recipe/network/FirestoreRecipesRepositoryTest.kt
Labels: enhancement

#277 Fix/search ingredient issue
  app/src/main/java/com/android/sample/model/ingredient/SearchIngredientViewModel.kt
  app/src/test/java/com/android/sample/model/ingredient/IngredientViewModelTest.kt
  app/src/test/java/com/android/sample/model/user/UserViewModelTest.kt
Labels: bug

#276 Feature/download recipe
  app/src/androidTest/java/com/android/sample/account/AccountScreenTest.kt
  app/src/androidTest/java/com/android/sample/account/EditAccountScreenTest.kt
  app/src/androidTest/java/com/android/sample/e2e/End2EndTest.kt
  app/src/androidTest/java/com/android/sample/offline/OfflineScreenTest.kt
  app/src/androidTest/java/com/android/sample/utils/RecipeImageTest.kt
  app/src/androidTest/java/com/android/sample/utils/RecipeListTest.kt
  app/src/main/java/com/android/sample/MainActivity.kt
  app/src/main/java/com/android/sample/model/recipe/RecipesViewModel.kt
  app/src/main/java/com/android/sample/resources/C.kt
  app/src/main/java/com/android/sample/ui/account/AccountScreen.kt
  app/src/main/java/com/android/sample/ui/offline/OfflineScreen.kt
  app/src/main/java/com/android/sample/ui/swipePage/SwipePage.kt
  app/src/main/java/com/android/sample/ui/utils/RecipeImage.kt
  app/src/main/java/com/android/sample/ui/utils/RecipeList.kt
  app/src/main/java/com/android/sample/utils/NetworkUtils.kt
  app/src/main/res/drawable/round_wifi_off_24.xml
  app/src/main/res/drawable/round_wifi_off_24_black.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/android/sample/model/recipe/RecipesViewModelTest.kt
Labels: enhancement

#284 bugfix : twice same img in swipe page
  app/src/main/java/com/android/sample/ui/swipePage/SwipePage.kt
Labels: bug

#288 Bugfix/ingredient uid
  app/src/main/java/com/android/sample/model/ingredient/IngredientViewModel.kt
  app/src/main/java/com/android/sample/model/ingredient/networkData/AggregatorIngredientRepository.kt
  app/src/main/java/com/android/sample/model/ingredient/networkData/FirestoreIngredientRepository.kt
  app/src/test/java/com/android/sample/model/ingredient/IngredientViewModelTest.kt
  app/src/test/java/com/android/sample/model/ingredient/network/AggregatorIngredientRepositoryTest.kt
  app/src/test/java/com/android/sample/model/ingredient/network/FirestoreIngredientRepositoryTest.kt
Labels: bug

#281 Enhance Ingredient Editing and Fridge UI for Improved User Experience
  app/src/androidTest/java/com/android/sample/fridge/EditFridgeItemTest.kt
  app/src/androidTest/java/com/android/sample/fridge/FridgeScreenTest.kt
  app/src/androidTest/java/com/android/sample/utils/ConfirmationPopUpTest.kt
  app/src/main/java/com/android/sample/model/user/UserViewModel.kt
  app/src/main/java/com/android/sample/resources/C.kt
  app/src/main/java/com/android/sample/ui/fridge/EditFridgeItemScreen.kt
  app/src/main/java/com/android/sample/ui/fridge/FridgeScreen.kt
  app/src/main/java/com/android/sample/ui/searchIngredient/SearchIngredientScreen.kt
  app/src/main/java/com/android/sample/ui/theme/Color.kt
  app/src/main/java/com/android/sample/ui/theme/Theme.kt
  app/src/main/java/com/android/sample/ui/utils/ConfirmationPopUp.kt
  app/src/main/res/drawable/close.png
  app/src/main/res/values/strings.xml
  app/src/test/java/com/android/sample/model/user/UserViewModelTest.kt
Labels: enhancement

#283 Feature Multiple Filtering
  app/src/androidTest/java/com/android/sample/utils/TimeDisplayTest.kt
  app/src/main/java/com/android/sample/model/filter/Filter.kt
  app/src/main/java/com/android/sample/model/recipe/RecipesViewModel.kt
  app/src/main/java/com/android/sample/model/recipe/networkData/FirestoreRecipesRepository.kt
  app/src/main/java/com/android/sample/ui/filter/FilterPage.kt
  app/src/main/java/com/android/sample/ui/utils/TimeDisplay.kt
  app/src/main/java/com/android/sample/ui/utils/ValueControl.kt
Labels: enhancement

#291 Fix Bug when ingredients are not correctly merge after editing
  app/src/main/java/com/android/sample/model/user/UserViewModel.kt
Labels: bug

#280 feat: update screen behaviors and tests for edit mode
  app/src/androidTest/java/com/android/sample/createRecipe/AddInstructionStepContentTest.kt
  app/src/androidTest/java/com/android/sample/createRecipe/OptionalInformationScreenTest.kt
  app/src/androidTest/java/com/android/sample/createRecipe/PublishRecipeScreenTest.kt
  app/src/androidTest/java/com/android/sample/createRecipe/RecipeListInstructionsScreenTest.kt
  app/src/androidTest/java/com/android/sample/createRecipe/RecipeStepScreenTest.kt
  app/src/androidTest/java/com/android/sample/createRecipe/TimePickerScreenTest.kt
  app/src/main/java/com/android/sample/MainActivity.kt
  app/src/main/java/com/android/sample/model/recipe/CreateRecipeViewModel.kt
  app/src/main/java/com/android/sample/model/recipe/RecipeBuilder.kt
  app/src/main/java/com/android/sample/model/user/UserViewModel.kt
  app/src/main/java/com/android/sample/resources/C.kt
  app/src/main/java/com/android/sample/ui/createRecipe/AddInstructionStepScreen.kt
  app/src/main/java/com/android/sample/ui/createRecipe/OptionalInformationScreen.kt
  app/src/main/java/com/android/sample/ui/createRecipe/PublishRecipeScreen.kt
  app/src/main/java/com/android/sample/ui/createRecipe/RecipeListInstructionsScreen.kt
  app/src/main/java/com/android/sample/ui/createRecipe/RecipeNameScreen.kt
  app/src/main/java/com/android/sample/ui/createRecipe/RecipeStepScreen.kt
  app/src/main/java/com/android/sample/ui/createRecipe/TimePickerScreen.kt
  app/src/main/java/com/android/sample/ui/navigation/NavigationActions.kt
  app/src/test/java/com/android/sample/model/recipe/CreateRecipeViewModelTest.kt
  app/src/test/java/com/android/sample/model/recipe/RecipeBuilderTest.kt
  app/src/test/java/com/android/sample/model/user/UserViewModelTest.kt
Labels: enhancement

#278 Feature/download fridge
  app/src/androidTest/java/com/android/sample/createRecipe/PublishRecipeScreenTest.kt
  app/src/androidTest/java/com/android/sample/e2e/End2EndTest.kt
  app/src/androidTest/java/com/android/sample/fridge/EditFridgeItemTest.kt
  app/src/androidTest/java/com/android/sample/fridge/FridgeScreenTest.kt
  app/src/androidTest/java/com/android/sample/utils/RecipeListTest.kt
  app/src/main/java/com/android/sample/MainActivity.kt
  app/src/main/java/com/android/sample/model/fridge/localData/Converters.kt
  app/src/main/java/com/android/sample/model/fridge/localData/FridgeItemDao.kt
  app/src/main/java/com/android/sample/model/fridge/localData/FridgeItemEntity.kt
  app/src/main/java/com/android/sample/model/fridge/localData/FridgeItemLocalRepository.kt
  app/src/main/java/com/android/sample/model/fridge/localData/FridgeItemRoomDB.kt
  app/src/main/java/com/android/sample/model/fridge/localData/RoomFridgeItemRepository.kt
  app/src/main/java/com/android/sample/model/ingredient/DefaultIngredientRepository.kt
  app/src/main/java/com/android/sample/model/ingredient/EntityMapper.kt
  app/src/main/java/com/android/sample/model/ingredient/IngredientRepository.kt
  app/src/main/java/com/android/sample/model/ingredient/IngredientViewModel.kt
  app/src/main/java/com/android/sample/model/ingredient/localData/IngredientDAO.kt
  app/src/main/java/com/android/sample/model/ingredient/localData/IngredientLocalRepository.kt
  app/src/main/java/com/android/sample/model/ingredient/localData/RoomIngredientRepository.kt
  app/src/main/java/com/android/sample/model/user/UserViewModel.kt
  app/src/main/java/com/android/sample/resources/C.kt
  app/src/main/java/com/android/sample/ui/account/AccountScreen.kt
  app/src/main/java/com/android/sample/ui/authentication/SignInScreen.kt
  app/src/main/java/com/android/sample/ui/fridge/EditFridgeItemScreen.kt
  app/src/main/java/com/android/sample/ui/fridge/FridgeScreen.kt
  app/src/test/java/com/android/sample/model/fridge/local/ConvertersTest.kt
  app/src/test/java/com/android/sample/model/fridge/local/FridgeItemRoomDBTest.kt
  app/src/test/java/com/android/sample/model/fridge/local/RoomFridgeItemRepositoryTest.kt
  app/src/test/java/com/android/sample/model/ingredient/DefaultIngredientRepositoryTest.kt
  app/src/test/java/com/android/sample/model/ingredient/local/RoomIngredientRepositoryTest.kt
  app/src/test/java/com/android/sample/model/ingredient/network/AggregatorIngredientRepositoryTest.kt
  app/src/test/java/com/android/sample/model/user/UserViewModelTest.kt
Labels: enhancement

#287 Chore/rename app and add logo
  app/src/androidTest/java/com/android/sample/account/AccountScreenTest.kt
  app/src/androidTest/java/com/android/sample/account/EditAccountScreenTest.kt
  app/src/androidTest/java/com/android/sample/createRecipe/RecipeProgressBarTest.kt
  app/src/androidTest/java/com/android/sample/utils/PlateSwipeScaffoldTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/sample/MainActivity.kt
  app/src/main/java/com/android/sample/ui/theme/Theme.kt
  app/src/main/plate_swipe_logo-playstore.png
  app/src/main/res/mipmap-anydpi-v26/plate_swipe_logo.xml
  app/src/main/res/mipmap-anydpi-v26/plate_swipe_logo_round.xml
  app/src/main/res/mipmap-hdpi/plate_swipe_logo.webp
  app/src/main/res/mipmap-hdpi/plate_swipe_logo_foreground.webp
  app/src/main/res/mipmap-hdpi/plate_swipe_logo_round.webp
  app/src/main/res/mipmap-mdpi/plate_swipe_logo.webp
  app/src/main/res/mipmap-mdpi/plate_swipe_logo_foreground.webp
  app/src/main/res/mipmap-mdpi/plate_swipe_logo_round.webp
  app/src/main/res/mipmap-xhdpi/plate_swipe_logo.webp
  app/src/main/res/mipmap-xhdpi/plate_swipe_logo_foreground.webp
  app/src/main/res/mipmap-xhdpi/plate_swipe_logo_round.webp
  app/src/main/res/mipmap-xxhdpi/plate_swipe_logo.webp
  app/src/main/res/mipmap-xxhdpi/plate_swipe_logo_foreground.webp
  app/src/main/res/mipmap-xxhdpi/plate_swipe_logo_round.webp
  app/src/main/res/mipmap-xxxhdpi/plate_swipe_logo.webp
  app/src/main/res/mipmap-xxxhdpi/plate_swipe_logo_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/plate_swipe_logo_round.webp
  app/src/main/res/values/plate_swipe_logo_background.xml
  app/src/main/res/values/strings.xml
  settings.gradle.kts
Labels: enhancement

#282 fix: prevent crash on blank recipe name in RecipeNameScreen
  app/src/androidTest/java/com/android/sample/createRecipe/RecipeNameScreenTest.kt
  app/src/main/java/com/android/sample/ui/createRecipe/RecipeNameScreen.kt
Labels: enhancement

#299 Edit Fridge UI improvement
  app/src/androidTest/java/com/android/sample/e2e/End2EndTest.kt
  app/src/androidTest/java/com/android/sample/fridge/FridgeScreenTest.kt
  app/src/androidTest/java/com/android/sample/screen/RecipeOverviewTest.kt
  app/src/androidTest/java/com/android/sample/utils/ConfirmationPopUpTest.kt
  app/src/androidTest/java/com/android/sample/utils/PlateSwipeAlertBoxTest.kt
  app/src/main/java/com/android/sample/MainActivity.kt
  app/src/main/java/com/android/sample/model/user/UserViewModel.kt
  app/src/main/java/com/android/sample/resources/C.kt
  app/src/main/java/com/android/sample/ui/createRecipe/AddInstructionStepScreen.kt
  app/src/main/java/com/android/sample/ui/fridge/EditFridgeItemScreen.kt
  app/src/main/java/com/android/sample/ui/fridge/FridgeScreen.kt
  app/src/main/java/com/android/sample/ui/searchIngredient/SearchIngredientScreen.kt
  app/src/main/java/com/android/sample/ui/utils/ConfirmationPopUp.kt
  app/src/main/java/com/android/sample/ui/utils/Counter.kt
  app/src/main/java/com/android/sample/ui/utils/PlateSwipeAlertBox.kt
  app/src/main/java/com/android/sample/ui/utils/RecipeList.kt
  app/src/main/java/com/android/sample/ui/utils/SearchBar.kt
Labels: enhancement

#302 Regenerate DB for Time and Difficulty functionality
  app/src/main/java/com/android/sample/resources/C.kt
Labels: enhancement

#300 Update README.md
  README.md
Labels: documentation

#303 test/end 2 end tests
  app/src/androidTest/java/com/android/sample/e2e/End2EndTest.kt
Labels: enhancement

#301 Refactor camera permission
  app/src/androidTest/java/com/android/sample/camera/CameraPermissionTest.kt
  app/src/main/java/com/android/sample/feature/camera/RequestCameraPermission.kt
  app/src/main/java/com/android/sample/ui/camera/CameraScanCodeBarScreen.kt
  app/src/main/java/com/android/sample/ui/camera/CameraTakePhotoScreen.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#305 Allow Adding Multiple Ingredients When Creating a New Recipe
  app/src/main/java/com/android/sample/model/ingredient/SearchIngredientViewModel.kt
Labels: bug

#308 Enhance TimePickerScreen Content Color and Usability
  app/src/main/java/com/android/sample/resources/C.kt
  app/src/main/java/com/android/sample/ui/createRecipe/TimePickerScreen.kt
  app/src/main/java/com/android/sample/ui/utils/TimeDisplay.kt
Labels: bug
