Repository PlateSwipe/PlateSwipe, pull requests merged in 2024-10, with the labels that each got.

#5 Update README with project description and features
  README.md
Labels: documentation

#49 Feature/google sign in screen
  app/build.gradle.kts
  app/src/androidTest/java/com/android/sample/authentication/SignInTest.kt
  app/src/main/java/com/android/sample/ui/authentication/SignIn.kt
  app/src/main/res/drawable/google_logo.png
  app/src/main/res/drawable/plateswipe_logo.png
  gradle/libs.versions.toml
Labels: enhancement

#51 Feature/google sign in
  app/build.gradle.kts
  app/src/androidTest/java/com/android/sample/authentication/SignInTest.kt
  app/src/main/java/com/android/sample/ui/authentication/SignIn.kt
  app/src/main/res/drawable/google_logo.png
  app/src/main/res/drawable/plateswipe_logo.png
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: enhancement

#108 feat: implement Recipe model based on ThemealDB API
  app/src/main/java/com/android/sample/model/recipe/Recipe.kt
Labels: enhancement

#110 Feature/user model
  app/src/main/java/com/android/sample/model/user/User.kt
  app/src/test/java/com/android/sample/model/user/UserTest.kt
Labels: enhancement

#113 Feature/implement recipe viewmodel
  app/src/main/java/com/android/sample/model/recipe/Recipe.kt
  app/src/main/java/com/android/sample/model/recipe/RecipeRepository.kt
  app/src/main/java/com/android/sample/model/recipe/RecipesViewModel.kt
  app/src/test/java/com/android/sample/model/recipe/RecipesViewModelTest.kt
Labels: enhancement

#116 Feature/repository mealdb
  app/src/main/java/com/android/sample/model/recipe/MealDBRecipeRepository.kt
  app/src/test/java/com/android/sample/model/recipe/MealDBRecipeRepositoryTest.kt
Labels: enhancement

#118 Add Tests for Recipe Creation and Enhance RecipesViewModel Testing
  app/src/main/java/com/android/sample/model/recipe/Recipe.kt
  app/src/main/java/com/android/sample/model/recipe/RecipesViewModel.kt
  app/src/test/java/com/android/sample/model/recipe/RecipeTest.kt
  app/src/test/java/com/android/sample/model/recipe/RecipesViewModelTest.kt
Labels: enhancement

#114 Feature/main page
  app/src/androidTest/java/com/android/sample/screen/MainScreenTest.kt
  app/src/androidTest/java/com/android/sample/screen/SwipePageTest.kt
  app/src/main/java/com/android/sample/MainActivity.kt
  app/src/main/java/com/android/sample/ui/swipePage/SwipePage.kt
  app/src/main/java/com/android/sample/ui/testScreens/MainScreen.kt
  app/src/main/java/com/android/sample/ui/theme/Color.kt
  app/src/main/java/com/android/sample/ui/theme/Theme.kt
  app/src/main/java/com/android/sample/ui/theme/Type.kt
  app/src/main/res/drawable/burger.jpeg
  app/src/main/res/drawable/salad.jpg
  app/src/main/res/drawable/timer.png
  gradle/libs.versions.toml
Labels: enhancement

#121 Feature/user database
  app/src/main/java/com/android/sample/model/user/User.kt
  app/src/main/java/com/android/sample/model/user/UserRepository.kt
  app/src/main/java/com/android/sample/model/user/UserRepositoryFirestore.kt
  app/src/test/java/com/android/sample/model/user/UserRepositoryFirestoreTest.kt
  app/src/test/java/com/android/sample/model/user/UserTest.kt
Labels: enhancement

#123 Figma
  README.md
Labels: figma

#129 Create build.yml
  .github/workflows/build.yml
Labels: enhancement

#125 Feature/swipe page
  app/build.gradle.kts
  app/src/androidTest/java/com/android/sample/screen/SwipePageTest.kt
  app/src/main/java/com/android/sample/MainActivity.kt
  app/src/main/java/com/android/sample/model/recipe/MealDBRecipeRepository.kt
  app/src/main/java/com/android/sample/model/recipe/RecipesViewModel.kt
  app/src/main/java/com/android/sample/resources/C.kt
  app/src/main/java/com/android/sample/ui/swipePage/SwipePage.kt
  app/src/main/java/com/android/sample/ui/theme/Color.kt
  app/src/main/java/com/android/sample/ui/theme/Theme.kt
  app/src/main/res/drawable/arrow.png
  app/src/main/res/drawable/star_rate.png
  app/src/main/res/values/strings.xml
  app/src/test/java/com/android/sample/model/recipe/MealDBRecipeRepositoryTest.kt
  app/src/test/java/com/android/sample/model/recipe/RecipesViewModelTest.kt
  gradle/libs.versions.toml
Labels: enhancement

#124 Feature/implement navigation from sign in to swipe screen and polish the project structure
  app/src/androidTest/java/com/android/sample/EmptyScreenTest.kt
  app/src/androidTest/java/com/android/sample/authentication/SignInTest.kt
  app/src/androidTest/java/com/android/sample/e2e/End2EndTest.kt
  app/src/androidTest/java/com/android/sample/fridge/FridgeScreenTest.kt
  app/src/androidTest/java/com/android/sample/recipe/CreateRecipeScreenTest.kt
  app/src/androidTest/java/com/android/sample/recipe/SearchRecipeScreenTest.kt
  app/src/androidTest/java/com/android/sample/screen/RecipeScreenTest.kt
  app/src/androidTest/java/com/android/sample/screen/SwipePageTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/sample/MainActivity.kt
  app/src/main/java/com/android/sample/MyService.kt
  app/src/main/java/com/android/sample/SecondActivity.kt
  app/src/main/java/com/android/sample/SimpleData.kt
  app/src/main/java/com/android/sample/ui/EmptyScreen.kt
  app/src/main/java/com/android/sample/ui/account/AccountScreen.kt
  app/src/main/java/com/android/sample/ui/authentication/SignIn.kt
  app/src/main/java/com/android/sample/ui/fridge/FridgeScreen.kt
  app/src/main/java/com/android/sample/ui/navigation/BottomNavigationMenu.kt
  app/src/main/java/com/android/sample/ui/navigation/NavigationActions.kt
  app/src/main/java/com/android/sample/ui/recipe/CreateRecipeScreen.kt
  app/src/main/java/com/android/sample/ui/recipe/SearchRecipeScreen.kt
  app/src/main/java/com/android/sample/ui/testScreens/AccountScreen.kt
  app/src/main/java/com/android/sample/ui/testScreens/AddRecipeScreen.kt
  app/src/main/java/com/android/sample/ui/testScreens/AuthScreen.kt
  app/src/main/java/com/android/sample/ui/testScreens/FridgeScreen.kt
  app/src/main/java/com/android/sample/ui/testScreens/IngredientScreen.kt
  app/src/main/java/com/android/sample/ui/testScreens/SearchScreen.kt
  app/src/main/java/com/android/sample/ui/theme/Type.kt
  app/src/main/res/drawable/account.xml
  app/src/main/res/font/montserrat_bold.ttf
  app/src/main/res/font/montserrat_light.ttf
  app/src/main/res/font/montserrat_regular.ttf
  app/src/test/java/com/android/sample/ExampleRobolectricTest.kt
  app/src/test/java/com/android/sample/ExampleUnitTest.kt
  app/src/test/java/com/android/sample/MyServiceTest.kt
  app/src/test/java/com/android/sample/NavigationTest.kt
  app/src/test/java/com/android/sample/PointTest.kt
  app/src/test/java/com/android/sample/screen/SecondScreen.kt
Labels: enhancement

#130 Feature/recipe overview
  app/src/androidTest/java/com/android/sample/screen/RecipeOverviewTest.kt
  app/src/main/java/com/android/sample/ui/recipeOverview/RecipeOverview.kt
Labels: enhancement

#142 Improve Testing
  app/src/androidTest/java/com/android/sample/screen/SwipePageTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/sample/MainActivity.kt
  app/src/main/java/com/android/sample/ui/navigation/NavigationActions.kt
  app/src/main/java/com/android/sample/ui/recipeOverview/RecipeOverview.kt
  app/src/main/java/com/android/sample/ui/swipePage/SwipePage.kt
Labels: enhancement

#128 Feature/enhance recipe search
  app/src/androidTest/java/com/android/sample/screen/RecipeOverviewTest.kt
  app/src/androidTest/java/com/android/sample/screen/SwipePageTest.kt
  app/src/main/java/com/android/sample/model/recipe/MealDBRecipeRepository.kt
  app/src/main/java/com/android/sample/model/recipe/MealDBRecipesRepository.kt
  app/src/main/java/com/android/sample/model/recipe/RecipeRepository.kt
  app/src/main/java/com/android/sample/model/recipe/RecipesViewModel.kt
  app/src/main/java/com/android/sample/resources/C.kt
  app/src/test/java/com/android/sample/model/recipe/MealDBRecipesRepositoryTest.kt
  app/src/test/java/com/android/sample/model/recipe/RecipesViewModelTest.kt
Labels: enhancement

#151 Feature/ingredient view model
  app/src/main/java/com/android/sample/model/ingredient/Ingredient.kt
  app/src/main/java/com/android/sample/model/ingredient/IngredientViewModel.kt
  app/src/main/java/com/android/sample/model/ingredient/OpenFoodFactsIngredientRepository.kt
  app/src/test/java/com/android/sample/model/ingredient/IngredientViewModelTest.kt
  app/src/test/java/com/android/sample/model/ingredient/OpenFoodFactsIngredientRepositoryTest.kt
Labels: enhancement

#156 Feature/recipe builder
  app/src/main/java/com/android/sample/model/recipe/RecipeBuilder.kt
  app/src/test/java/com/android/sample/model/recipe/RecipeBuilderTest.kt
Labels: enhancement

#155 Feature/image storage
  app/src/main/java/com/android/sample/model/image/ImageRepository.kt
  app/src/main/java/com/android/sample/model/image/ImageRepositoryFirebase.kt
  app/src/main/java/com/android/sample/resources/C.kt
  app/src/test/java/com/android/sample/model/imageRepositoryFirebase/ImageRepositoryFirebaseTest.kt
  app/src/test/resources/images/Muscle mice sticker.jpg
Labels: enhancement

#157 Feature/ create recipe viewmodel
  app/src/main/java/com/android/sample/model/recipe/CreateRecipeViewModel.kt
  app/src/main/java/com/android/sample/resources/C.kt
  app/src/test/java/com/android/sample/model/recipe/CreateRecipeViewModelTest.kt
Labels: enhancement

#158 Add interfaces to manage FilterPage and RecipeOverview
  app/src/main/java/com/android/sample/model/filter/FilterPageViewModel.kt
  app/src/main/java/com/android/sample/model/recipe/RecipeOverviewViewModel.kt
  app/src/main/java/com/android/sample/model/recipe/RecipesViewModel.kt
  app/src/main/java/com/android/sample/ui/filter/FilterPage.kt
  app/src/main/java/com/android/sample/ui/recipeOverview/RecipeOverview.kt
Labels: enhancement
