Repository PlateSwipe/PlateSwipe, pull requests merged in 2024-11, with the labels that each got.

#150 Feature/backend firestore random method
  app/src/main/java/com/android/sample/model/recipe/FirestoreRecipesRepository.kt
  app/src/main/java/com/android/sample/resources/C.kt
  app/src/test/java/com/android/sample/model/recipe/FirestoreRecipesRepositoryTest.kt
Labels: enhancement

#161 Feature/account screen
  app/src/androidTest/java/com/android/sample/account/AccountScreenTest.kt
  app/src/main/java/com/android/sample/ui/account/AccountScreen.kt
  app/src/main/java/com/android/sample/ui/utils/RecipeList.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#147 Camera Scanner
  app/build.gradle.kts
  app/src/androidTest/java/com/android/sample/camera/CameraPermissionTest.kt
  app/src/androidTest/java/com/android/sample/camera/CameraScanCodeBarScreenTest.kt
  app/src/androidTest/java/com/android/sample/camera/CameraViewTest.kt
  app/src/androidTest/java/com/android/sample/camera/scan/CodeBarAnalyzerTest.kt
  app/src/androidTest/java/com/android/sample/e2e/End2EndTest.kt
  app/src/androidTest/java/com/android/sample/fridge/FridgeScreenTest.kt
  app/src/debug/res/values/strings.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/sample/MainActivity.kt
  app/src/main/java/com/android/sample/feature/camera/CameraActions.kt
  app/src/main/java/com/android/sample/feature/camera/CameraUtils.kt
  app/src/main/java/com/android/sample/feature/camera/CameraView.kt
  app/src/main/java/com/android/sample/feature/camera/RequestCameraPermission.kt
  app/src/main/java/com/android/sample/feature/camera/scan/CodeBarAnalyzer.kt
  app/src/main/java/com/android/sample/resources/C.kt
  app/src/main/java/com/android/sample/ui/camera/CameraScanCodeBarScreen.kt
  app/src/main/java/com/android/sample/ui/fridge/FridgeScreen.kt
  app/src/main/java/com/android/sample/ui/navigation/NavigationActions.kt
  app/src/main/res/drawable/account.xml
  app/src/main/res/drawable/addicon.xml
  app/src/main/res/drawable/barcode.png
  app/src/main/res/drawable/downloadicon.xml
  app/src/main/res/drawable/fridgeicon.xml
  app/src/main/res/drawable/mainpageicon.xml
  app/src/main/res/drawable/searchicon.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/test/java/com/android/sample/feature/camera/scan/HandleBarcodeDetectionTest.kt
  app/src/test/java/com/android/sample/model/user/UserRepositoryFirestoreTest.kt
  gradle/libs.versions.toml
Labels: enhancement, help wanted

#169 Chore/ci config fix
  .github/workflows/apkDebug.yml
  .github/workflows/build.yml
  .github/workflows/ci.yml
Labels: bug, documentation, enhancement

#171 Chore/build apk debug
  .github/workflows/apkDebug.yml
Labels: bug, documentation

#167 Feature/ingredient database firestore
  app/src/androidTest/java/com/android/sample/camera/CameraScanCodeBarScreenTest.kt
  app/src/main/java/com/android/sample/model/ingredient/AggregatorIngredientRepository.kt
  app/src/main/java/com/android/sample/model/ingredient/FirestoreIngredientRepository.kt
  app/src/main/java/com/android/sample/model/ingredient/Ingredient.kt
  app/src/main/java/com/android/sample/model/ingredient/IngredientViewModel.kt
  app/src/main/java/com/android/sample/resources/C.kt
  app/src/test/java/com/android/sample/model/ingredient/AggregatorIngredientRepositoryTest.kt
  app/src/test/java/com/android/sample/model/ingredient/FirestoreIngredientRepositoryTest.kt
  app/src/test/java/com/android/sample/model/ingredient/IngredientViewModelTest.kt
  app/src/test/java/com/android/sample/model/user/UserViewModelTest.kt
Labels: enhancement

#173 Feature/recipe builder getters
  app/src/main/java/com/android/sample/model/recipe/RecipeBuilder.kt
  app/src/test/java/com/android/sample/model/recipe/RecipeBuilderTest.kt
Labels: enhancement

#149 Feature/UI utils top bar correction
  app/src/androidTest/java/com/android/sample/utils/PlateSwipeScaffoldTest.kt
  app/src/main/java/com/android/sample/resources/C.kt
  app/src/main/java/com/android/sample/ui/utils/PlateSwipeScaffold.kt
  app/src/main/res/drawable/chef_s_hat.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#180 Feature/ingredient field additions
  app/src/androidTest/java/com/android/sample/camera/CameraScanCodeBarScreenTest.kt
  app/src/main/java/com/android/sample/model/ingredient/FirestoreIngredientRepository.kt
  app/src/main/java/com/android/sample/model/ingredient/Ingredient.kt
  app/src/main/java/com/android/sample/model/ingredient/IngredientViewModel.kt
  app/src/main/java/com/android/sample/model/ingredient/OpenFoodFactsIngredientRepository.kt
  app/src/main/java/com/android/sample/resources/C.kt
  app/src/test/java/com/android/sample/model/ingredient/AggregatorIngredientRepositoryTest.kt
  app/src/test/java/com/android/sample/model/ingredient/FirestoreIngredientRepositoryTest.kt
  app/src/test/java/com/android/sample/model/ingredient/IngredientViewModelTest.kt
  app/src/test/java/com/android/sample/model/ingredient/OpenFoodFactsIngredientRepositoryTest.kt
  app/src/test/java/com/android/sample/model/user/UserViewModelTest.kt
Labels: enhancement

#185 Feature/`CreateRecipeViewModel`getters
  app/src/main/java/com/android/sample/model/recipe/CreateRecipeViewModel.kt
  app/src/test/java/com/android/sample/model/recipe/CreateRecipeViewModelTest.kt
Labels: enhancement

#168 Enhance Overview UI design and add new tests
  app/src/androidTest/java/com/android/sample/animation/LoadingAnimationTest.kt
  app/src/androidTest/java/com/android/sample/animation/LoadingCookTest.kt
  app/src/androidTest/java/com/android/sample/screen/RecipeOverviewTest.kt
  app/src/androidTest/java/com/android/sample/utils/TagTest.kt
  app/src/main/java/com/android/sample/animation/LoadingAnimation.kt
  app/src/main/java/com/android/sample/animation/LoadingCook.kt
  app/src/main/java/com/android/sample/resources/C.kt
  app/src/main/java/com/android/sample/ui/authentication/SignInScreen.kt
  app/src/main/java/com/android/sample/ui/recipeOverview/RecipeOverview.kt
  app/src/main/java/com/android/sample/ui/swipePage/SwipePage.kt
  app/src/main/java/com/android/sample/ui/theme/Theme.kt
  app/src/main/java/com/android/sample/ui/theme/Type.kt
  app/src/main/java/com/android/sample/ui/utils/RecipeList.kt
  app/src/main/java/com/android/sample/ui/utils/Tag.kt
  app/src/main/res/drawable/cook_loading.png
  app/src/main/res/values/strings.xml
Labels: enhancement

#186 Improve UI depends on persona's feedbacks
  app/src/androidTest/java/com/android/sample/authentication/SignInScreenTest.kt
  app/src/androidTest/java/com/android/sample/screen/RecipeOverviewTest.kt
  app/src/androidTest/java/com/android/sample/screen/SwipePageTest.kt
  app/src/androidTest/java/com/android/sample/utils/TagTest.kt
  app/src/main/java/com/android/sample/resources/C.kt
  app/src/main/java/com/android/sample/ui/authentication/SignInScreen.kt
  app/src/main/java/com/android/sample/ui/recipeOverview/RecipeOverview.kt
  app/src/main/java/com/android/sample/ui/swipePage/SwipePage.kt
  app/src/main/java/com/android/sample/ui/theme/Color.kt
  app/src/main/java/com/android/sample/ui/theme/Theme.kt
  app/src/main/java/com/android/sample/ui/utils/PlateSwipeScaffold.kt
  app/src/main/java/com/android/sample/ui/utils/Tag.kt
  app/src/main/res/drawable/dislike.png
  app/src/main/res/drawable/like.png
  app/src/main/res/values/strings.xml
Labels: enhancement

#141 Feature/create recipe page
  app/src/androidTest/java/com/android/sample/createRecipe/AddInstructionStepContentTest.kt
  app/src/androidTest/java/com/android/sample/createRecipe/ChefImageTest.kt
  app/src/androidTest/java/com/android/sample/createRecipe/CreateRecipeScreenTest.kt
  app/src/androidTest/java/com/android/sample/createRecipe/IconDropdownMenuTest.kt
  app/src/androidTest/java/com/android/sample/createRecipe/PublishRecipeScreenTest.kt
  app/src/androidTest/java/com/android/sample/createRecipe/RecipeIngredientsScreenTest.kt
  app/src/androidTest/java/com/android/sample/createRecipe/RecipeInstructionsScreenTest.kt
  app/src/androidTest/java/com/android/sample/createRecipe/RecipeNameScreenTest.kt
  app/src/androidTest/java/com/android/sample/createRecipe/RecipeProgressBarTest.kt
  app/src/androidTest/java/com/android/sample/createRecipe/RecipeStepScreenTest.kt
  app/src/androidTest/java/com/android/sample/e2e/End2EndTest.kt
  app/src/main/java/com/android/sample/MainActivity.kt
  app/src/main/java/com/android/sample/model/recipe/CreateRecipeViewModel.kt
  app/src/main/java/com/android/sample/model/recipe/RecipeBuilder.kt
  app/src/main/java/com/android/sample/resources/C.kt
  app/src/main/java/com/android/sample/ui/createRecipe/AddInstructionStepScreen.kt
  app/src/main/java/com/android/sample/ui/createRecipe/ChefImage.kt
  app/src/main/java/com/android/sample/ui/createRecipe/CreateRecipeScreen.kt
  app/src/main/java/com/android/sample/ui/createRecipe/IconDropdownMenu.kt
  app/src/main/java/com/android/sample/ui/createRecipe/PublishRecipeScreen.kt
  app/src/main/java/com/android/sample/ui/createRecipe/RecipeIngredientsScreen.kt
  app/src/main/java/com/android/sample/ui/createRecipe/RecipeInstructionsScreen.kt
  app/src/main/java/com/android/sample/ui/createRecipe/RecipeNameScreen.kt
  app/src/main/java/com/android/sample/ui/createRecipe/RecipeProgressBar.kt
  app/src/main/java/com/android/sample/ui/createRecipe/RecipeStepScreen.kt
  app/src/main/java/com/android/sample/ui/navigation/NavigationActions.kt
  app/src/main/java/com/android/sample/ui/theme/Color.kt
  app/src/main/java/com/android/sample/ui/theme/Type.kt
  app/src/main/res/drawable/arrow_down.xml
  app/src/main/res/drawable/assignment.xml
  app/src/main/res/drawable/axe.xml
  app/src/main/res/drawable/chef_image_in_egg.png
  app/src/main/res/drawable/chef_s_hat.xml
  app/src/main/res/drawable/chef_standing.png
  app/src/main/res/drawable/crop_original.xml
  app/src/main/res/drawable/fire.xml
  app/src/main/res/drawable/mortar.xml
  app/src/main/res/drawable/salt.xml
  app/src/main/res/drawable/whisk.xml
  app/src/main/res/font/meera_inimai_regular.ttf
  app/src/main/res/font/roboto_bold.ttf
  app/src/main/res/font/roboto_regular.ttf
  app/src/main/res/values/strings.xml
  app/src/test/java/com/android/sample/NavigationTest.kt
  app/src/test/java/com/android/sample/model/recipe/CreateRecipeViewModelTest.kt
  app/src/test/java/com/android/sample/model/recipe/RecipeBuilderTest.kt
Labels: enhancement

#191 Feature/Create Recipe `RecipeListInstructionsScreen`
  app/src/androidTest/java/com/android/sample/createRecipe/AddInstructionStepContentTest.kt
  app/src/androidTest/java/com/android/sample/createRecipe/RecipeListInstructionsScreenTest.kt
  app/src/androidTest/java/com/android/sample/utils/PlateSwipeButtonTest.kt
  app/src/main/java/com/android/sample/MainActivity.kt
  app/src/main/java/com/android/sample/model/recipe/CreateRecipeViewModel.kt
  app/src/main/java/com/android/sample/model/recipe/RecipeBuilder.kt
  app/src/main/java/com/android/sample/resources/C.kt
  app/src/main/java/com/android/sample/ui/createRecipe/AddInstructionStepScreen.kt
  app/src/main/java/com/android/sample/ui/createRecipe/RecipeListInstructionsScreen.kt
  app/src/main/java/com/android/sample/ui/navigation/BottomNavigationMenu.kt
  app/src/main/java/com/android/sample/ui/navigation/NavigationActions.kt
  app/src/main/java/com/android/sample/ui/utils/PlateSwipeButton.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#172 feature/take Photo
  app/src/androidTest/java/com/android/sample/camera/CameraTakePhotoScreenTest.kt
  app/src/androidTest/java/com/android/sample/createRecipe/AddInstructionStepContentTest.kt
  app/src/androidTest/java/com/android/sample/createRecipe/ChefImageTest.kt
  app/src/androidTest/java/com/android/sample/createRecipe/CreateRecipeScreenTest.kt
  app/src/androidTest/java/com/android/sample/createRecipe/PublishRecipeScreenTest.kt
  app/src/androidTest/java/com/android/sample/createRecipe/RecipeAddImageScreenTest.kt
  app/src/androidTest/java/com/android/sample/createRecipe/RecipeIngredientsScreenTest.kt
  app/src/androidTest/java/com/android/sample/createRecipe/RecipeInstructionsScreenTest.kt
  app/src/androidTest/java/com/android/sample/createRecipe/RecipeListInstructionsScreenTest.kt
  app/src/androidTest/java/com/android/sample/createRecipe/RecipeNameScreenTest.kt
  app/src/androidTest/java/com/android/sample/createRecipe/RecipeStepScreenTest.kt
  app/src/androidTest/java/com/android/sample/e2e/End2EndTest.kt
  app/src/debug/res/values/strings.xml
  app/src/main/java/com/android/sample/MainActivity.kt
  app/src/main/java/com/android/sample/feature/camera/CameraActions.kt
  app/src/main/java/com/android/sample/feature/camera/CameraUtils.kt
  app/src/main/java/com/android/sample/feature/camera/CameraView.kt
  app/src/main/java/com/android/sample/model/image/ImageRepository.kt
  app/src/main/java/com/android/sample/model/image/ImageRepositoryFirebase.kt
  app/src/main/java/com/android/sample/model/recipe/CreateRecipeViewModel.kt
  app/src/main/java/com/android/sample/model/recipe/RecipeBuilder.kt
  app/src/main/java/com/android/sample/resources/C.kt
  app/src/main/java/com/android/sample/ui/camera/CameraScanCodeBarScreen.kt
  app/src/main/java/com/android/sample/ui/camera/CameraTakePhotoScreen.kt
  app/src/main/java/com/android/sample/ui/createRecipe/ChefImage.kt
  app/src/main/java/com/android/sample/ui/createRecipe/RecipeAddImageScreen.kt
  app/src/main/java/com/android/sample/ui/createRecipe/RecipeListInstructionsScreen.kt
  app/src/main/java/com/android/sample/ui/fridge/FridgeScreen.kt
  app/src/main/java/com/android/sample/ui/navigation/NavigationActions.kt
  app/src/main/java/com/android/sample/ui/theme/Type.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/android/sample/feature/camera/CameraUtilsTest.kt
  app/src/test/java/com/android/sample/model/imageRepositoryFirebase/ImageRepositoryFirebaseTest.kt
  app/src/test/java/com/android/sample/model/recipe/CreateRecipeViewModelTest.kt
  app/src/test/java/com/android/sample/model/recipe/RecipeBuilderTest.kt
  app/src/test/resources/images/Scoobygourmand_Moin90.jpg
  app/src/test/resources/images/scoobygourmand_90.jpg
  app/src/test/resources/images/scoobygourmand_normal.jpg
  gradle/libs.versions.toml
Labels: enhancement

#201 Feature/img url
  app/src/main/java/com/android/sample/model/image/ImageRepository.kt
  app/src/main/java/com/android/sample/model/image/ImageRepositoryFirebase.kt
  app/src/main/java/com/android/sample/model/recipe/CreateRecipeViewModel.kt
  app/src/main/java/com/android/sample/model/recipe/FirestoreRecipesRepository.kt
  app/src/main/java/com/android/sample/model/recipe/Recipe.kt
  app/src/main/java/com/android/sample/model/recipe/RecipeBuilder.kt
  app/src/main/java/com/android/sample/resources/C.kt
  app/src/main/java/com/android/sample/ui/swipePage/SwipePage.kt
  app/src/test/java/com/android/sample/model/imageRepositoryFirebase/ImageRepositoryFirebaseTest.kt
  app/src/test/java/com/android/sample/model/recipe/CreateRecipeViewModelTest.kt
  app/src/test/java/com/android/sample/model/recipe/RecipeBuilderTest.kt
  app/src/test/java/com/android/sample/model/recipe/RecipeTest.kt
Labels: enhancement

#174 Feature/import image
  app/build.gradle.kts
  app/src/androidTest/java/com/android/sample/createRecipe/RecipeAddImageScreenTest.kt
  app/src/androidTest/java/com/android/sample/fridge/FridgeScreenTest.kt
  app/src/androidTest/res/drawable/scoobygourmand_normal.jpg
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/sample/MainActivity.kt
  app/src/main/java/com/android/sample/feature/camera/CameraUtils.kt
  app/src/main/java/com/android/sample/resources/C.kt
  app/src/main/java/com/android/sample/ui/createRecipe/ChefImage.kt
  app/src/main/java/com/android/sample/ui/createRecipe/RecipeAddImageScreen.kt
  app/src/main/java/com/android/sample/ui/fridge/FridgeScreen.kt
  app/src/main/java/com/android/sample/ui/navigation/NavigationActions.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/android/sample/feature/camera/CameraUtilsTest.kt
  gradle/libs.versions.toml
Labels: enhancement

#197 Create searching ingredient screen
  app/src/androidTest/java/com/android/sample/camera/CameraScanCodeBarScreenTest.kt
  app/src/androidTest/java/com/android/sample/createRecipe/IngredientSearchScreenTest.kt
  app/src/androidTest/java/com/android/sample/createRecipe/ListIngredientScreenTest.kt
  app/src/androidTest/java/com/android/sample/createRecipe/RecipeIngredientsScreenTest.kt
  app/src/main/java/com/android/sample/MainActivity.kt
  app/src/main/java/com/android/sample/animation/LoadingCook.kt
  app/src/main/java/com/android/sample/model/ingredient/AggregatorIngredientRepository.kt
  app/src/main/java/com/android/sample/model/ingredient/IngredientViewModel.kt
  app/src/main/java/com/android/sample/model/ingredient/OpenFoodFactsIngredientRepository.kt
  app/src/main/java/com/android/sample/resources/C.kt
  app/src/main/java/com/android/sample/ui/camera/CameraScanCodeBarScreen.kt
  app/src/main/java/com/android/sample/ui/createRecipe/IngredientSearchScreen.kt
  app/src/main/java/com/android/sample/ui/createRecipe/ListIngredientScreen.kt
  app/src/main/java/com/android/sample/ui/createRecipe/RecipeIngredientsScreen.kt
  app/src/main/java/com/android/sample/ui/navigation/BottomNavigationMenu.kt
  app/src/main/java/com/android/sample/ui/navigation/NavigationActions.kt
  app/src/main/java/com/android/sample/ui/theme/Color.kt
  app/src/main/java/com/android/sample/ui/theme/Theme.kt
  app/src/main/java/com/android/sample/ui/theme/Type.kt
  app/src/main/java/com/android/sample/ui/utils/PlateSwipeScaffold.kt
  app/src/main/java/com/android/sample/ui/utils/SearchBar.kt
  app/src/main/res/drawable/add.png
  app/src/main/res/drawable/scanner.png
  app/src/main/res/values/strings.xml
  app/src/test/java/com/android/sample/model/ingredient/AggregatorIngredientRepositoryTest.kt
  app/src/test/java/com/android/sample/model/ingredient/IngredientViewModelTest.kt
Labels: enhancement

#194 Enhance Create Recipe Screens UI and functionality
  app/src/androidTest/java/com/android/sample/createRecipe/AddInstructionStepContentTest.kt
  app/src/androidTest/java/com/android/sample/createRecipe/IconDropdownMenuTest.kt
  app/src/androidTest/java/com/android/sample/createRecipe/PublishRecipeScreenTest.kt
  app/src/main/java/com/android/sample/MainActivity.kt
  app/src/main/java/com/android/sample/model/recipe/CreateRecipeViewModel.kt
  app/src/main/java/com/android/sample/resources/C.kt
  app/src/main/java/com/android/sample/ui/createRecipe/AddInstructionStepScreen.kt
  app/src/main/java/com/android/sample/ui/createRecipe/IconDropdownMenu.kt
  app/src/main/java/com/android/sample/ui/createRecipe/PublishRecipeScreen.kt
  app/src/main/java/com/android/sample/ui/createRecipe/RecipeNameScreen.kt
  app/src/main/java/com/android/sample/ui/createRecipe/RecipeProgressBar.kt
  app/src/main/java/com/android/sample/ui/createRecipe/RecipeStepScreen.kt
  app/src/main/res/drawable/chef_image_in_egg1.png
  app/src/main/res/values/strings.xml
  app/src/test/java/com/android/sample/model/recipe/CreateRecipeViewModelTest.kt
Labels: enhancement

#209 ci : Add APK-Release.yml workflow
  .github/workflows/APK-Release.yml
  .github/workflows/ci.yml
  app/build.gradle.kts
Labels: bug

#195 feature/link-account-recipes
  app/src/androidTest/java/com/android/sample/account/AccountScreenTest.kt
  app/src/androidTest/java/com/android/sample/utils/RecipeListTest.kt
  app/src/main/java/com/android/sample/MainActivity.kt
  app/src/main/java/com/android/sample/model/user/UserViewModel.kt
  app/src/main/java/com/android/sample/resources/C.kt
  app/src/main/java/com/android/sample/ui/account/AccountScreen.kt
  app/src/main/java/com/android/sample/ui/navigation/NavigationActions.kt
  app/src/main/java/com/android/sample/ui/recipeOverview/RecipeOverview.kt
  app/src/main/java/com/android/sample/ui/swipePage/SwipePage.kt
  app/src/main/java/com/android/sample/ui/utils/RecipeList.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/android/sample/model/user/UserViewModelTest.kt
Labels: enhancement

#217 Refactor/change name of recipe parameters
  app/src/androidTest/java/com/android/sample/account/AccountScreenTest.kt
  app/src/androidTest/java/com/android/sample/e2e/End2EndTest.kt
  app/src/androidTest/java/com/android/sample/utils/RecipeListTest.kt
  app/src/main/java/com/android/sample/model/recipe/CreateRecipeViewModel.kt
  app/src/main/java/com/android/sample/model/recipe/FirestoreRecipesRepository.kt
  app/src/main/java/com/android/sample/model/recipe/Recipe.kt
  app/src/main/java/com/android/sample/model/recipe/RecipeBuilder.kt
  app/src/main/java/com/android/sample/model/user/UserViewModel.kt
  app/src/main/java/com/android/sample/ui/recipeOverview/RecipeOverview.kt
  app/src/main/java/com/android/sample/ui/swipePage/SwipePage.kt
  app/src/main/java/com/android/sample/ui/utils/RecipeList.kt
  app/src/test/java/com/android/sample/model/recipe/CreateRecipeViewModelTest.kt
  app/src/test/java/com/android/sample/model/recipe/FirestoreRecipesRepositoryTest.kt
  app/src/test/java/com/android/sample/model/recipe/MealDBRecipesRepositoryTest.kt
  app/src/test/java/com/android/sample/model/recipe/RecipeBuilderTest.kt
  app/src/test/java/com/android/sample/model/recipe/RecipeTest.kt
  app/src/test/java/com/android/sample/model/recipe/RecipesViewModelTest.kt
  app/src/test/java/com/android/sample/model/user/UserViewModelTest.kt
Labels: enhancement

#216 Refactor `IconType` class to use a single string for dynamic resource resolution
  app/src/androidTest/java/com/android/sample/createRecipe/IconDropdownMenuTest.kt
  app/src/main/java/com/android/sample/model/recipe/CreateRecipeViewModel.kt
  app/src/main/java/com/android/sample/model/recipe/IconType.kt
  app/src/main/java/com/android/sample/resources/C.kt
  app/src/main/java/com/android/sample/ui/createRecipe/AddInstructionStepScreen.kt
  app/src/main/java/com/android/sample/ui/createRecipe/IconDropdownMenu.kt
  app/src/test/java/com/android/sample/model/recipe/IconTypeTest.kt
Labels: enhancement

#213 Fix/forced bananas
  app/src/androidTest/java/com/android/sample/createRecipe/RecipeIngredientsScreenTest.kt
  app/src/androidTest/java/com/android/sample/e2e/End2EndTest.kt
  app/src/main/java/com/android/sample/MainActivity.kt
  app/src/main/java/com/android/sample/ui/createRecipe/RecipeIngredientsScreen.kt
Labels: bug

#222 Unified testing resources
  app/src/androidTest/java/com/android/sample/account/AccountScreenTest.kt
  app/src/androidTest/java/com/android/sample/createRecipe/IngredientSearchScreenTest.kt
  app/src/androidTest/java/com/android/sample/createRecipe/ListIngredientScreenTest.kt
  app/src/androidTest/java/com/android/sample/e2e/End2EndTest.kt
  app/src/androidTest/java/com/android/sample/screen/FilterPageTest.kt
  app/src/androidTest/java/com/android/sample/screen/RecipeOverviewTest.kt
  app/src/androidTest/java/com/android/sample/screen/SwipePageTest.kt
  app/src/main/java/com/android/sample/ui/utils/SampleClasses.kt
  app/src/test/java/com/android/sample/model/ingredient/AggregatorIngredientRepositoryTest.kt
  app/src/test/java/com/android/sample/model/ingredient/FirestoreIngredientRepositoryTest.kt
  app/src/test/java/com/android/sample/model/ingredient/IngredientViewModelTest.kt
  app/src/test/java/com/android/sample/model/recipe/CreateRecipeViewModelTest.kt
  app/src/test/java/com/android/sample/model/recipe/FirestoreRecipesRepositoryTest.kt
  app/src/test/java/com/android/sample/model/recipe/RecipesViewModelTest.kt
  app/src/test/java/com/android/sample/model/user/UserRepositoryFirestoreTest.kt
  app/src/test/java/com/android/sample/model/user/UserViewModelTest.kt
Labels: enhancement

#224 Implement FilterPage and SwipePage modifications based on userFeedback
  app/src/androidTest/java/com/android/sample/e2e/End2EndTest.kt
  app/src/androidTest/java/com/android/sample/screen/FilterPageTest.kt
  app/src/androidTest/java/com/android/sample/screen/SwipePageTest.kt
  app/src/main/java/com/android/sample/animation/LoadingAnimation.kt
  app/src/main/java/com/android/sample/model/filter/Filter.kt
  app/src/main/java/com/android/sample/model/filter/FilterPageViewModel.kt
  app/src/main/java/com/android/sample/model/recipe/RecipesViewModel.kt
  app/src/main/java/com/android/sample/resources/C.kt
  app/src/main/java/com/android/sample/ui/filter/FilterPage.kt
  app/src/main/java/com/android/sample/ui/swipePage/SwipePage.kt
  app/src/main/java/com/android/sample/ui/utils/PlateSwipeScaffold.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/android/sample/model/recipe/IconTypeTest.kt
  app/src/test/java/com/android/sample/model/recipe/RecipesViewModelTest.kt
Labels: enhancement

#218 Feature/ingredient url
  app/src/androidTest/java/com/android/sample/NetworkTest.kt
  app/src/androidTest/java/com/android/sample/camera/CameraScanCodeBarScreenTest.kt
  app/src/androidTest/java/com/android/sample/e2e/End2EndTest.kt
  app/src/main/java/com/android/sample/feature/camera/CameraUtils.kt
  app/src/main/java/com/android/sample/model/image/ImageRepositoryFirebase.kt
  app/src/main/java/com/android/sample/model/image/ImageUploader.kt
  app/src/main/java/com/android/sample/model/ingredient/AggregatorIngredientRepository.kt
  app/src/main/java/com/android/sample/model/ingredient/FirestoreIngredientRepository.kt
  app/src/main/java/com/android/sample/model/ingredient/Ingredient.kt
  app/src/main/java/com/android/sample/model/ingredient/IngredientViewModel.kt
  app/src/main/java/com/android/sample/model/ingredient/OpenFoodFactsIngredientRepository.kt
  app/src/main/java/com/android/sample/resources/C.kt
  app/src/main/java/com/android/sample/ui/camera/CameraScanCodeBarScreen.kt
  app/src/main/java/com/android/sample/ui/utils/SampleClasses.kt
  app/src/test/java/com/android/sample/model/imageRepositoryFirebase/ImageUploaderTest.kt
  app/src/test/java/com/android/sample/model/ingredient/AggregatorIngredientRepositoryTest.kt
  app/src/test/java/com/android/sample/model/ingredient/IngredientViewModelTest.kt
  app/src/test/java/com/android/sample/model/ingredient/OpenFoodFactsIngredientRepositoryTest.kt
Labels: enhancement

#225 Improve and fix random fetch of recipe
  app/src/androidTest/java/com/android/sample/screen/RecipeOverviewTest.kt
  app/src/androidTest/java/com/android/sample/screen/SwipePageTest.kt
  app/src/main/java/com/android/sample/model/recipe/FirestoreRecipesRepository.kt
  app/src/main/java/com/android/sample/model/recipe/RecipesViewModel.kt
  app/src/main/java/com/android/sample/resources/C.kt
  app/src/main/java/com/android/sample/ui/recipeOverview/RecipeOverview.kt
  app/src/main/java/com/android/sample/ui/swipePage/SwipePage.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/android/sample/model/recipe/FirestoreRecipesRepositoryTest.kt
  app/src/test/java/com/android/sample/model/recipe/RecipesViewModelTest.kt
Labels: bug, enhancement

#220 Feature/Implement all previous features with the new `Instruction` data class
  app/src/androidTest/java/com/android/sample/createRecipe/AddInstructionStepContentTest.kt
  app/src/androidTest/java/com/android/sample/createRecipe/PublishRecipeScreenTest.kt
  app/src/androidTest/java/com/android/sample/createRecipe/RecipeListInstructionsScreenTest.kt
  app/src/androidTest/java/com/android/sample/screen/RecipeOverviewTest.kt
  app/src/androidTest/java/com/android/sample/utils/RecipeListTest.kt
  app/src/main/java/com/android/sample/model/recipe/CreateRecipeViewModel.kt
  app/src/main/java/com/android/sample/model/recipe/FirestoreRecipesRepository.kt
  app/src/main/java/com/android/sample/model/recipe/Instruction.kt
  app/src/main/java/com/android/sample/model/recipe/MealDBRecipesRepository.kt
  app/src/main/java/com/android/sample/model/recipe/Recipe.kt
  app/src/main/java/com/android/sample/model/recipe/RecipeBuilder.kt
  app/src/main/java/com/android/sample/resources/C.kt
  app/src/main/java/com/android/sample/ui/createRecipe/AddInstructionStepScreen.kt
  app/src/main/java/com/android/sample/ui/createRecipe/ListIngredientScreen.kt
  app/src/main/java/com/android/sample/ui/createRecipe/RecipeListInstructionsScreen.kt
  app/src/main/java/com/android/sample/ui/recipeOverview/RecipeOverview.kt
  app/src/main/java/com/android/sample/ui/utils/SampleClasses.kt
  app/src/test/java/com/android/sample/model/recipe/CreateRecipeViewModelTest.kt
  app/src/test/java/com/android/sample/model/recipe/FirestoreRecipesRepositoryTest.kt
  app/src/test/java/com/android/sample/model/recipe/MealDBRecipesRepositoryTest.kt
  app/src/test/java/com/android/sample/model/recipe/RecipeBuilderTest.kt
  app/src/test/java/com/android/sample/model/recipe/RecipeTest.kt
  app/src/test/java/com/android/sample/model/recipe/RecipesViewModelTest.kt
Labels: enhancement

#227 Feature/delete created recipe
  app/src/androidTest/java/com/android/sample/account/AccountScreenTest.kt
  app/src/androidTest/java/com/android/sample/utils/RecipeListTest.kt
  app/src/main/java/com/android/sample/model/user/UserViewModel.kt
  app/src/main/java/com/android/sample/resources/C.kt
  app/src/main/java/com/android/sample/ui/account/AccountScreen.kt
  app/src/main/java/com/android/sample/ui/utils/RecipeList.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/android/sample/model/user/UserViewModelTest.kt
Labels: enhancement

#230 Feature/enhance creation of a recipe
  app/src/androidTest/java/com/android/sample/createRecipe/RecipeAddImageScreenTest.kt
  app/src/androidTest/java/com/android/sample/screen/RecipeOverviewTest.kt
  app/src/main/java/com/android/sample/ui/createRecipe/ListIngredientScreen.kt
  app/src/main/java/com/android/sample/ui/createRecipe/RecipeAddImageScreen.kt
  app/src/main/java/com/android/sample/ui/createRecipe/RecipeNameScreen.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#242 fix: handle blank instruction validation in AddInstructionStepScreen
  app/src/androidTest/java/com/android/sample/createRecipe/AddInstructionStepContentTest.kt
  app/src/main/java/com/android/sample/ui/createRecipe/AddInstructionStepScreen.kt
Labels: bug

#238 Fix `SearchIngredientScreen` Issues and Improve Generalization
  app/src/androidTest/java/com/android/sample/createRecipe/ListIngredientScreenTest.kt
  app/src/androidTest/java/com/android/sample/createRecipe/RecipeIngredientsScreenTest.kt
  app/src/androidTest/java/com/android/sample/createRecipe/RecipeNameScreenTest.kt
  app/src/androidTest/java/com/android/sample/e2e/End2EndTest.kt
  app/src/androidTest/java/com/android/sample/search/SearchIngredientScreenTest.kt
  app/src/androidTest/java/com/android/sample/utils/ConfirmationPopUpTest.kt
  app/src/androidTest/java/com/android/sample/utils/ImageBoxTest.kt
  app/src/main/java/com/android/sample/MainActivity.kt
  app/src/main/java/com/android/sample/model/ingredient/IngredientViewModel.kt
  app/src/main/java/com/android/sample/model/ingredient/SearchIngredientViewModel.kt
  app/src/main/java/com/android/sample/resources/C.kt
  app/src/main/java/com/android/sample/ui/camera/CameraScanCodeBarScreen.kt
  app/src/main/java/com/android/sample/ui/createRecipe/ListIngredientScreen.kt
  app/src/main/java/com/android/sample/ui/createRecipe/RecipeIngredientsScreen.kt
  app/src/main/java/com/android/sample/ui/createRecipe/RecipeNameScreen.kt
  app/src/main/java/com/android/sample/ui/navigation/NavigationActions.kt
  app/src/main/java/com/android/sample/ui/searchIngredient/SearchIngredientScreen.kt
  app/src/main/java/com/android/sample/ui/utils/ConfirmationPopUp.kt
  app/src/main/java/com/android/sample/ui/utils/IngredientImageBox.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/android/sample/model/ingredient/IngredientViewModelTest.kt
Labels: bug

#236 Feature add and delete instruction button
  app/src/androidTest/java/com/android/sample/createRecipe/AddInstructionStepContentTest.kt
  app/src/androidTest/java/com/android/sample/createRecipe/RecipeListInstructionsScreenTest.kt
  app/src/androidTest/java/com/android/sample/utils/PlateSwipeAlertBoxTest.kt
  app/src/main/java/com/android/sample/resources/C.kt
  app/src/main/java/com/android/sample/ui/createRecipe/AddInstructionStepScreen.kt
  app/src/main/java/com/android/sample/ui/createRecipe/ListIngredientScreen.kt
  app/src/main/java/com/android/sample/ui/createRecipe/RecipeListInstructionsScreen.kt
  app/src/main/java/com/android/sample/ui/navigation/NavigationActions.kt
  app/src/main/java/com/android/sample/ui/utils/PlateSwipeAlertBox.kt
  app/src/main/java/com/android/sample/ui/utils/PlateSwipeButton.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#244 test: add Android tests for IconTypeTest class
  app/src/androidTest/java/com/android/sample/model/recipe/IconTypeTest.kt
  app/src/test/java/com/android/sample/model/recipe/IconTypeTest.kt
Labels: enhancement

#237 Feature/fridge backend
  app/src/main/java/com/android/sample/model/fridge/FridgeItem.kt
  app/src/main/java/com/android/sample/model/user/User.kt
  app/src/main/java/com/android/sample/model/user/UserRepositoryFirestore.kt
  app/src/main/java/com/android/sample/model/user/UserViewModel.kt
  app/src/main/java/com/android/sample/resources/C.kt
  app/src/main/java/com/android/sample/ui/utils/SampleClasses.kt
  app/src/test/java/com/android/sample/model/user/UserRepositoryFirestoreTest.kt
  app/src/test/java/com/android/sample/model/user/UserTest.kt
  app/src/test/java/com/android/sample/model/user/UserViewModelTest.kt
Labels: enhancement

#245 Feature/total time screen
  app/src/androidTest/java/com/android/sample/createRecipe/RecipeListInstructionsScreenTest.kt
  app/src/androidTest/java/com/android/sample/createRecipe/TimePickerScreenTest.kt
  app/src/androidTest/java/com/android/sample/e2e/End2EndTest.kt
  app/src/main/java/com/android/sample/MainActivity.kt
  app/src/main/java/com/android/sample/resources/C.kt
  app/src/main/java/com/android/sample/ui/createRecipe/RecipeListInstructionsScreen.kt
  app/src/main/java/com/android/sample/ui/createRecipe/TimePickerScreen.kt
  app/src/main/java/com/android/sample/ui/navigation/NavigationActions.kt
  app/src/main/res/values/strings.xml
Labels: enhancement
